# Input/Output/Name
train_data: "dataset/train.txt"
val_data: "dataset/val.txt"
output_path: "outputs"
model_path: "checkpoints"
load_chkpt: null # continue training
name: "test"

# Training parameters
epochs: 60
batchsize: 128

# Optimizer configurations
optimizer: "AdamW"
scheduler: "CosineAnnealingWarmUpRestarts"
lr: 0.0
T_0: 20
T_mult: 2.0
eta_max: 0.003
T_up: 1
gamma: 0.5

# Parameters for model architectures
